### ISSUE TITLE
Support for headmod

### ISSUE THREAD

**Issue by sleepymanakete** [FlailingFog/KK-Blender-Porter-Pack#147] opened 2022-04-05 22:30 UTC
Hi! 
When I try exporting yelan, the pmx exporter only exports her textures not her model/pmx. From my testing, it seems to have something to do with the face type
card and mods:
[card](https://cdn.discordapp.com/attachments/447115249997578241/958021486633967657/Koikatu_F_20220226211751665__.png) 
[mod](https://www.mediafire.com/file/rfprgezok6d1hip/%255BJM%255Dyelan.zipmod/file) 
[mod 2](https://www.mediafire.com/file/1db06ueogsdut8m/%255BSZY%255Dyelan_headmod.zipmod/file)

**Comment by MediaMoots** [comment] 2022-04-21 06:33
It's possible to export head modded characters, the issue is that some headmods rename the shapekeys breaking the Finalize PMX script.

In Yelan's case, the tang and namida shapekeys were renamed...

**Comment by MediaMoots** [comment] 2022-04-21 06:35
Also, there was a bug with the Exporter that will be fixed in PR #138 but i think KKBP won't work for now.

**Comment by sleepymanakete** [comment] 2022-04-29 00:21
ok, thanks for the fix! :)
hopefully the shape keys won't be too hard to solve 🙏

**Comment by sleepymanakete** [comment] 2022-07-14 16:34
Tried exporting Yelan with the v6 beta and her model doesn't import correctly in blender. her outfits aren't hidden and ignores the rig selection I choose. not sure if its the shapekey issue again or something else so I thought I'd let you know about this.

**Comment by k-0-del** [comment] 2022-07-31 19:00
i also can't export anything other than default cards i guess its about face mods again

**Comment by sleepymanakete** [comment] 2022-08-24 22:28
yeah i believe its head mods again. tried a different character and no pmx file is given to me. 
https://mega.nz/folder/GfYHTRZQ#KkL36HTCV_gf3GTDSENA6w

**Comment by MediaMoots** [comment] 2022-09-27 06:16
Could you try the latest master? V3.92 might fix this

**Closed** 2022-11-05 22:09 UTC
