### ISSUE TITLE
GUI revamp + explanation for possible new features

### ISSUE THREAD

**Issue by TheMaskedMan00** [FlailingFog/KK-Blender-Porter-Pack#220] opened 2022-08-16 18:15 UTC
![KKBP GUI Prototype](https://user-images.githubusercontent.com/46354545/184946586-79532ccb-9400-45a7-a000-f2b35ce28fc5.png)

Here is a quick little drawing I made in Google Drawings. It's just a prototype but it shows what features should be added.

KKBP plugin:
1. Make exporting all outfits optional
2. Ability to export .mat files. this can be achieved with the help of my little plugin, i can share the code with you guys when i finish polishing it. 

Both?:

1. Export all UV maps. This should be relatively straight forward. I have the vanilla plus shaders as .shader in unity so I can use them for the characters, Only issue is that it will only work properly if i use GME, Because GME exports all UV maps and the shader uses the different UV maps for positioning things. And we probably dont even need to export them, as I'm pretty sure they are always the same regardless of what character you use (maybe the male and female ones differ. So we could just have this uv data stored in the KKBP blender file, and have it apply the other uv maps when its done.

Blender Plugin:
1. Add option to switch between old baking system and new baking system.
2. Not really a suggestion but the V6 of the blender plugin is terribly slow when selecting (prep for export) compared to the older version. Maybe its just because I am on a laptop, but it takes around 20 mins for me to prep for export on the newer V6, where as in the older versions it would take 2 Minutes. Maybe this is due to the fact that all outfits are exported now instead of just one, or that the entire code was changed, I'm really not sure. Maybe add some info in the console to show what It's doing when we prep for export, since all i see is warnings about the GUI draw rect or something like that.

Final note, I assume you are not willing to share the source code to the KKBP plugin itself nor provide us with any other form of communication as all my previous questions about it have been ignored. Maybe I'm wrong and you just have not had the time to read them, or maybe you have your own reasons. Whatever the reason, I would still appreciate a response about the source code of the KKBP plugin as I would really like to take a look at it and maybe fix some small bugs I encountered. That is all I have to say for today. Thanks for reading.

**Comment by MediaMoots** [comment] 2022-08-17 01:49
Hi, thanks for the UI suggestion, I will look into it.

> Make exporting all outfits optional

That was added a few days ago in PR #138 

> Ability to export .mat files. this can be achieved with the help of my little plugin, i can share the code with you guys when i finish polishing it.

What is the purpose for .mat files?

> Export all UV maps.

KKBP Plugin already exports all UV maps, so not sure what the issue is?

> Final note, I assume you are not willing to share the source code to the KKBP plugin itself nor provide us with any other form of communication as all my previous questions about it have been ignored.

Ah yeah, sorry, I didn't have the time to respond.
About the source code please see https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/165#issuecomment-1146645433
And unfortunately, I am not available on discord, but GitHub issues are fine : )

P.S.
Please note that KKBP Plugin exports everything (UVs, material data, textures, character info and more) except maybe a few things I overlooked such as separate eye textures (Already fixed in PR #138), so it would be great if you checked that PR for updates before requesting features that have already been added. Thanks! : )

**Comment by TheMaskedMan00** [comment] 2022-08-17 06:06
> Hi, thanks for the UI suggestion, I will look into it.
> 
> > Make exporting all outfits optional
> 
> That was added a few days ago in PR #138
> 
> > Ability to export .mat files. this can be achieved with the help of my little plugin, i can share the code with you guys when i finish polishing it.
> 
> What is the purpose for .mat files?
> 
> > Export all UV maps.
> 
> KKBP Plugin already exports all UV maps, so not sure what the issue is?
> 
> > Final note, I assume you are not willing to share the source code to the KKBP plugin itself nor provide us with any other form of communication as all my previous questions about it have been ignored.
> 
> Ah yeah, sorry, I didn't have the time to respond. About the source code please see [#165 (comment)](https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/165#issuecomment-1146645433) And unfortunately, I am not available on discord, but GitHub issues are fine for me : )
> 
> P.S. Please note that KKBP Plugin exports everything (UVs, material data, textures, character info and more) except maybe a few things I overlooked such as separate eye textures (Already fixed in PR #138), so it would be great if you checked that PR for updates before requesting features that have already been added. Thanks! : )

the purpose of the .mat files is so we can directly use the characters in unity with all the correct shader material parameters. I have shaders that are reverse engineered from the original game shaders. This already works in my plugin but it would be cool if you could add it to yours.

**Comment by FlailingFog** [comment] 2022-08-19 15:58
> 1. Add option to switch between old baking system and new baking system.

The new baking system is better because it bakes the new UV maps as well. Is there a reason you'd want the old one?

**Closed** 2023-05-21 14:55 UTC
Labels: enhancement, Fixed in next release
