### ISSUE TITLE
Mesh missing vertices after import to Blender

### ISSUE THREAD

**Issue by jexom** [FlailingFog/KK-Blender-Porter-Pack#261] opened 2022-09-21 06:20 UTC
Blender Version: 3.1.2
Add-on Version: 6.0
Koikatsu Version: Sunshine BetterRepack R3.1

After importing to blender the model is missing body vertices. Exported with a single outfit option enabled on an outfit 5
![image](https://user-images.githubusercontent.com/6067696/191428564-8fbb4939-ff84-46d6-97bb-ac0c5f6c1222.png)
![image](https://user-images.githubusercontent.com/6067696/191428631-1ae42914-ec5e-4a1a-aea5-43d0847b5631.png)

The card in question:
![KK_291301](https://user-images.githubusercontent.com/6067696/191428761-605d0243-6f56-4987-a07a-c4cb33771233.png)
And the mods needed:
[Oozora Subaru.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9613563/Oozora.Subaru.zip)

**Comment by jexom** [comment] 2022-09-21 07:01
The issue seems to be in the head model, as exporting with a different head does not create the issue

**Comment by jexom** [comment] 2022-09-21 07:04
Possibly related to #147

**Comment by MediaMoots** [comment] 2022-09-27 06:14
Fixed in V3.92:
![image](https://user-images.githubusercontent.com/81146974/192445929-5e91a007-ef5e-4ed2-8932-ccbc7606202e.png)

However, the clipping is caused by the inner shirt, but that's more of a rendering issue, I think.

**Closed** 2022-09-27 06:15 UTC
Labels: bug
